### ISSUE TITLE
[bug]linux no such file or directory: ./koko-moni

### ISSUE THREAD

**Issue by SkinAir** [burpheart/koko-moni#4]
ubuntu
![image](https://user-images.githubusercontent.com/71880910/226118737-1ef7f63d-909c-4e92-ac53-201c6612cf85.png)
debian
![image](https://user-images.githubusercontent.com/71880910/226118751-907f2881-8608-4db9-a7db-5eba880243f6.png)
windows正常
![image](https://user-images.githubusercontent.com/71880910/226118779-38f8ab71-daff-4774-88c1-7ad27a036fc9.png)

**Comment by SkinAir** [comment]
原因是系统缺少一个名为 "libc.musl-x86_64.so.1" 的共享库文件
sudo apt-get install musl-tools
随后正常运行

**Comment by burpheart** [comment]
我忘记开静态链接了 下个版本会静态链接 把libc库编译进去

________________________________
发件人: WinkAir ***@***.***>
发送时间: 2023年3月19日星期日 上午1:10
收件人: burpheart/koko-moni ***@***.***>
抄送: Subscribed ***@***.***>
主题: Re: [burpheart/koko-moni] [bug]linux no such file or directory: ./koko-moni (Issue #4)


原因是系统缺少一个名为 "libc.musl-x86_64.so.1" 的共享库文件
sudo apt-get install musl-tools
随后正常运行

―
